#!/bin/bash

DIR=$(cd -- "$(dirname -- "${BASH_SOURCE}")" &>/dev/null && pwd)
HOSTNAME=$(cat /proc/sys/kernel/hostname)
RESET="\033[0m"
GREEN="\033[32m"
BLUE="\033[34m"


if [ ! -f "/usr/local/bin/start-sway" ]; then
    echo "start-sway not found in /usr/local/bin/"
    echo "installing it requires sudo"
    sudo install -Dm755 "$DIR/start-sway" /usr/local/bin/start-sway
fi


DRY_RUN=""
for arg in "$@"; do
    if [ "$arg" = "-n" ] || [ "$arg" = "--dry-run" ]; then
        DRY_RUN="-n"
        echo -e "-- DRY-RUN --"
    fi
done

echo -e "    ${GREEN}Stowing 'main' profile...${BLUE}"
stow $DRY_RUN -v -d "$DIR" -t ~ main 2>&1 | sed "s/^/       /"

echo -e "\n${RESET}Complete!"