# clean up cava when sway is reset
exec_always pkill -9 -f cava && pkill -9 -f cava-waybar

exec swayidle -w \
	timeout 300 'wlock -a 524f67 -i 403d52 -c 000000 -f eb6f92' \
	timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
	before-sleep 'wlock -a 524f67 -i 403d52 -c 000000 -f eb6f92'

exec ~/scripts/workspace-renamer.py
exec ~/scripts/rofi-polkit

exec foot --server
exec wl-paste --watch bash -c 'sleep 0.1 && cliphist store'
exec wlsunset -l 25 -L 67
exec udiskie -s

exec systemd-inhibit --who="sway" --why="user" --what=handle-power-key --mode=block sleep infinity