input type:touchpad {
	dwt enabled
	tap enabled
	drag_lock disabled
	natural_scroll enabled
	middle_emulation enabled
}

input 1133:49298:Logitech_G102_LIGHTSYNC_Gaming_Mouse {
	natural_scroll disabled
	dwt false
	accel_profile "flat"
	pointer_accel 0
}

input type:keyboard {
	xkb_layout "us"
}

input type:tablet_tool {
	map_to_output eDP-1
	calibration_matrix -1 0 1 0 -1 1
}