assign [app_id="^app.zen_browser.zen$"] workspace number 1
assign [app_id="^vesktop$"] workspace number 2
assign [app_id="^com.rtosta.zapzap$"] workspace number 2

for_window [app_id="^vesktop$"] layout tabbed
for_window [app_id="^com.rtosta.zapzap$"] layout tabbed