font pango:NotoSansM Nerd Font 10
output * bg $surface solid_color

# target                 title          bg            text   indicator       border
client.focused           $pine         $pine         $text  $foam             $pine
client.focused_inactive  $muted        $muted        $text  $subtle           $muted
client.unfocused         $highlightmed $highlightmed $text  $highlighthigh    $highlightmed
client.urgent            $love         $love         $base  $rose             $love
client.placeholder       $base         $base         $text  $overlay          $overlay
client.background        $base

default_border normal 2
default_floating_border normal 2

gaps inner 2px
gaps outer 0px