#!/bin/bash
LOG_DIR="$HOME/.cache/tofi-runlog"
LATEST=$(ls -t "$LOG_DIR"/tofi-runlog-*.log 2>/dev/null | head -n1)
if [ -n "$LATEST" ]; then
	footclient -T "tofi-runlog-viewer" sh -c "LESSOPEN= less +F \"$LATEST\""
else
	echo "No tofi-run logs yet."
fi